services:
  cleanup:
    entrypoint:
      - /bin/rm
      - -fr
      - dist
      - src/datime.egg-info
    image: ghcr.io/williamjacksn/datime-dev
    init: true
    volumes:
      - ./:/home/python/datime
    working_dir: /home/python/datime

  py-build:
    entrypoint:
      - /home/python/venv/bin/python
      - -m
      - build
    image: ghcr.io/williamjacksn/datime-dev
    init: true
    volumes:
      - ./:/home/python/datime
    working_dir: /home/python/datime

  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/williamjacksn/datime-dev
    init: true
    volumes:
      - ./:/home/python/datime
    working_dir: /home/python/datime
